server:
  port: 8282
  
  
spring:
  application:
    name: Customers-Services  

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  