server:
  port: 8888
  
  
spring:
  application:
    name: API-Gateway-Services  

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  