server:
  port: 8181
  
spring:
  application:
    name: Accounts-Services  

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   